name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio tensorflow numpy pandas scipy tqdm scikit-learn
        pip install dgl dglgo -f https://data.dgl.ai/wheels/repo.html

    - name: Run KGAT on small dataset
      run: |
        python Main.py --data_name small --cf_batch_size 1 --kg_batch_size 1 --test_batch_size 1 --n_epoch 1 --K 1 --evaluate_every 9999
